server:
  port: 1010
  servlet:
    context-path: /

spring:
  application:
    name: haohao-fast
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.haohao.fast.domain
  global-config:
    banner: false
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      update-strategy: ignored

jwt:
  header: authorization
  secret: abcdefghijklmnopqrstuvwxyz
  expireTime: 60
  prefix: Bearer

jasypt:
  encryptor:
    password: 123456
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

minio:
  url: http://localhost:9000
  user: admin
  password: admin123
  bucketName: haohao-fast
  allowedFileTypes: JPG,GIF,DOC,DOCX,XLS,XLSX,MP4,MP3