spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/haohao-fast?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
          username: root
          password: root
        slave:
          url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
          username: root
          password: root
  redis:
    host: localhost
    port: 6379
    timeout: 10000ms
    database: 1
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  rabbitmq:
    addresses: localhost
    port: 15672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual

logging:
  file:
    path: /Users/haohao/logs/haohao-fast

springfox:
  documentation:
    swagger-ui:
      enabled: true
